.PHONY : all
#all : documentation executable
DOC ?= fileName
SOURCES = $(DOC).m.nw
ROOT ?= definition

all : documentation tangle clean

weave: $(SOURCES)
	noweave -delay -index $(SOURCES) > $(DOC).tex
tangle: $(SOURCES)
	notangle -R$(ROOT) $(SOURCES) > $(DOC).m
documentation: weave
	pdflatex $(DOC).tex; pdflatex $(DOC).tex; pdflatex $(DOC).tex
#executable: tangle
#	gcc NR.c -lm -o NR

.PHONY: clean
clean:
	rm -f *.log *.aux
full_clean:
	rm -f *.log *.aux *.tex *.m *.pdf
